# Generated by Django 5.0 on 2023-12-07 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('cuisine', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('logo', models.ImageField(default='', upload_to='kitchen/images')),
                ('banner', models.ImageField(default='', upload_to='kitchen/images')),
                ('opening_hours', models.CharField(max_length=50)),
                ('order_accept_time', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
