# Generated by Django 5.0 on 2023-12-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='', upload_to='kitchen/images')),
                ('category', models.CharField(choices=[('soup', 'Soup'), ('noodles soup', 'Noodles Soup'), ('chicken', 'Chicken'), ('beef', 'Beef'), ('seafood', 'Seafood'), ('vegetables', 'Vegetables'), ('pasta', 'Pasta')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='kitchen.kitchen')),
            ],
        ),
    ]
