# Generated by Django 5.0 on 2023-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('soup', 'Soup'), ('meat', 'Meat'), ('seafood', 'Seafood'), ('vegetables', 'Vegetables'), ('pasta', 'Pasta')], max_length=20),
        ),
    ]
