# Generated by Django 5.0 on 2024-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_contact_number_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
